#pragma once

enum class UIElement {
    BACKGROUND,
    FIELD_HIGHLIGHT,
    BLUE_CARD_BACK, RED_CARD_BACK,
    RESTART_BTN, RESTART_BTN_PRESSED, EXIT_BTN, EXIT_BTN_PRESSED,
    MAP_OVERLAY_TOP_SHROUDED, MAP_OVERLAY_BOTTOM_SHROUDED, MAP_OVERLAY_FADE_TOP_MAP, MAP_OVERLAY_FADE_BOTTOM_MAP,
    MSG_WAIT_FOR_BLUE, MSG_WAIT_FOR_RED,
    VICTORY_COMMON_TOP, VICTORY_BLUE_MID, VICTORY_RED_MID, VICTORY_TIED, VICTORY_COMMON_BOTTOM,
    AVAILABLE_MOVE,
    MENU_BACK_TOP, MENU_BACK_BOTTOM, MENU, MENU_BTN, MENU_BTN_PRESSED,
    SPLASH

};